### ISSUE TITLE
Cache: Build info file does not contain storage layout

### ISSUE THREAD

**Issue by hiendaovinh** [OpenZeppelin/openzeppelin-foundry-upgrades#4]
Hi, thanks for the repository, it helps a lot to setup upgrades with foundry.
There is a problem with foundry output `storageLayout` after the first successful run which requires us to `yarn clean` all the time before testing. I'm not sure it's an issue with this or foundry itself.
Step to reproduce:
1. Done everything documented in README and have your first successful test with `yarn test --ffi -vvv` 
2. Change anything in the test files to invalidate the output artifacts
3. Run `yarn test --ffi -vvv` again. It should fail now because of missing storage layout.
4. `yarn clean && yarn test --ffi -vvv` again. It runs successfully. 
5. Now every time I want to test, I need to `yarn clean` =(

**Comment by 0x3bfc** [comment]
Thanks @ericglau for the tech explanation. The `--force` works for the CI.

**Comment by RickVM** [comment]
I'm running into this problem when executing forge scripts, even after `forge clean` or when using `--force`.

Both fixes do work for us when running `forge test --ffi --force`, but not when running `forge script script/DeployContracts.s.sol:DeployContracts \
  --fork-url ${RPC_URL} \
  --broadcast \
  -vvvv \
  --private-key ${DEPLOYER_PRIVATE_KEY} \
  --ffi \
  --force`
```

In both cases, I have manually verified and can see that out/build-info does contain a file which seems to have storageLayouts.

2024-01-14T12:11:55.161932Z ERROR cheatcodes: non-empty stderr input=["npx", "@openzeppelin/upgrades-core@^1.31.0", "validate", "out/build-info", "--contract", "src/TimePiecePassport.sol:TimePiecePassport"] stderr="/Users/rick/.npm/_npx/db46e24580d42758/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/build-info-file.js:101\n                throw new error_1.ValidateCommandError(`Build info file ${buildInfoFilePath} does not contain storage layout.`, () => STORAGE_LAYOUT_HELP);\n                      ^\n\nValidateCommandError: Build info file out/build-info/61112cbfc9266bc57d70b1becfbe095a.json does not contain storage layout.\n\nIf using Hardhat, include the 'storageLayout' output selection in your Hardhat config:\n  module.exports = {\n    solidity: {\n      settings: {\n        outputSelection: {\n          '*': {\n            '*': ['storageLayout'],\n          },\n        },\n      },\n    },\n  };\nThen recompile your contracts with 'npx hardhat clean && npx hardhat compile' and try again.\n\nIf using Foundry, include the \"storageLayout\" extra output in foundry.toml:\n  [profile.default]\n  build_info = true\n  extra_output = [\"storageLayout\"]\nThen recompile your contracts with 'forge clean && forge build' and try again.\n    at readBuildInfo (/Users/rick/.npm/_npx/db46e24580d42758/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/build-info-file.js:101:23)\n    at async getBuildInfoFiles (/Users/rick/.npm/_npx/db46e24580d42758/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/build-info-file.js:41:12)\n    at async validateUpgradeSafety (/Users/rick/.npm/_npx/db46e24580d42758/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/validate-upgrade-safety.js:22:28)\n    at async main (/Users/rick/.npm/_npx/db46e24580d42758/node_modules/@openzeppelin/upgrades-core/dist/cli/validate.js:30:24)\n    at async run (/Users/rick/.npm/_npx/db46e24580d42758/node_modules/@openzeppelin/upgrades-core/dist/cli/cli.js:6:5)\n\nNode.js v18.17.0\n"
```

**Comment by ericglau** [comment]
@RickVM Thanks for reporting, I see this as well and am working on a fix.  This happens due to a recent change in Foundry that affects the output format for scripts.  As a workaround for now, you can `forge clean`, `forge test`, then `forge script` in that order without modifying anything in between those steps.

**Comment by ericglau** [comment]
The issue with `forge script` above is fixed in the linked PRs.  You can get the fix by either updating your submodule for this repository, or by updating your installed npm package of `@openzeppelin/upgrades-core`.

Note that the limitation mentioned in my [earlier comment](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/4#issuecomment-1852436281) still exists -- that is, you still need to either run `forge clean` before running scripts or tests, or use `--force` with `forge script` or `forge test` to do a full compilation in order for upgrade safety validations to work.

Otherwise, you will get an error like `Build info file is not from a full compilation.`
