### ISSUE TITLE
Latest Foundry Forge breaks OZ Upgrades

### ISSUE THREAD

**Issue by Magicking** [OpenZeppelin/openzeppelin-foundry-upgrades#51]
Using
```
%> forge --version
forge 0.2.0 (c486fca34 2024-05-06T14:17:57.000000000Z)
```

it spits out these errors 

```
Ran 1 test for test/deployment/Upgrades.t.sol:DeploymentTest
[FAIL. Reason: setup failed: revert: Failed to run upgrade safety validation: /home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/validate/run.js:152
        const content = solcInput.sources[source].content;
                                                  ^

TypeError: Cannot read properties of undefined (reading 'content')
    at checkNamespaceSolidityVersion (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/validate/run.js:152:51)
    at validate (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/validate/run.js:89:9)
    at runValidations (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/validations.js:23:41)
    at validateBuildInfoContracts (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/validations.js:14:29)
    at validateUpgradeSafety (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/cli/validate/validate-upgrade-safety.js:23:74)
    at async main (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/cli/validate.js:30:24)
    at async run (/home/XXX/.npm/_npx/fb3494f8bab08a4d/node_modules/@openzeppelin/upgrades-core/dist/cli/cli.js:6:5)

Node.js v21.7.3
] setUp() (gas: 0)
Suite result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 4.56s (0.00ns CPU time)
```

while this version

```
%> forge --version
forge 0.2.0 (72bc4f4e6 2024-05-08T13:15:15.000000000Z)
```

works perfectly fine.

Regarding the content of Upgrades.t.sol, it's a test that imports a deployment Script and performs the Upgrades check to verify that the proxy upgrades are working.

### Other information

```
%> git submodule
 bb4ceea94d6f10eeb5b41dc2391c6c8bf8e734ef lib/forge-std (v1.8.1)
 dbb6104ce834628e473d2173bbc9d47f81a9eec3 lib/openzeppelin-contracts (v5.0.0-12-gdbb6104c)
 723f8cab09cdae1aca9ec9cc1cfa040c2d4b06c1 lib/openzeppelin-contracts-upgradeable (v5.0.2)
 359589365aeba6cf41d39bae69867446b194e582 lib/openzeppelin-foundry-upgrades (v0.2.1)
```

**Comment by ericglau** [comment]
This was reported and fixed in https://github.com/foundry-rs/foundry/issues/7878.

Can you run foundryup again?  I tested that it works with the latest version `forge 0.2.0 (a4d79ac 2024-05-09T00:18:10.247407000Z)`.
