### ISSUE TITLE
 throw new error_1.ValidateCommandError(`Build info file ${buildInfoFilePath} must contain Solidity compiler input

### ISSUE THREAD

**Issue by tbag9527** [OpenZeppelin/openzeppelin-foundry-upgrades#60]
[FAIL. Reason: setup failed: revert: Failed to run upgrade safety validation: C:\Users\king\AppData\Local\npm-cache\_npx\fb3494f8bab08a4d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:101
            throw new error_1.ValidateCommandError(`Build info file ${buildInfoFilePath} must contain Solidity compiler input, output, and solcVersion.`);
                  ^

ValidateCommandError: Build info file out\build-info\01ab43501ba30d7b860c74f93be53dd9.json must contain Solidity compiler input, output, and solcVersion.

    at readBuildInfo (C:\Users\king\AppData\Local\npm-cache\_npx\fb3494f8bab08a4d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:101:19)
    at async getBuildInfoFiles (C:\Users\king\AppData\Local\npm-cache\_npx\fb3494f8bab08a4d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\build-info-file.js:45:12)
    at async validateUpgradeSafety (C:\Users\king\AppData\Local\npm-cache\_npx\fb3494f8bab08a4d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate\validate-upgrade-safety.js:22:28)
    at async main (C:\Users\king\AppData\Local\npm-cache\_npx\fb3494f8bab08a4d\node_modules\@openzeppelin\upgrades-core\dist\cli\validate.js:30:24)
    at async run (C:\Users\king\AppData\Local\npm-cache\_npx\fb3494f8bab08a4d\node_modules\@openzeppelin\upgrades-core\dist\cli\cli.js:6:5)

Node.js v20.14.0

**Comment by ericglau** [comment]
Ensure you have followed the steps in the ["Before Running" section](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades?tab=readme-ov-file#before-running) of the readme.

If you still encounter the error, please share your foundry.toml file and the build info file that causes the error, if possible (note that it will include the source code of all your contracts).

**Comment by ericglau** [comment]
Closing this issue as this looks like a configuration issue as described above. Feel free to reopen if you are still encountering the problem.
