### ISSUE TITLE
Defender deployment has error "Payload Too Large"

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/openzeppelin-foundry-upgrades#8]
When performing a [deployment through Defender](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/blob/main/DEFENDER.md), the following error may occur:
```
status: 413,\n    statusText: 'Payload Too Large',\n    data: 'HTTP content length exceeded 10485760 bytes.'
```

This is caused by all of the contracts being included in the build info file when Foundry does a first compilation, which results in the file being too large.

This is a known issue and a fix to optimize this will be included in an upcoming release of the Defender SDK.

**WORKAROUND**: Make a small edit (e.g. change whitespace) in the contract that you want to deploy, which forces Foundry to recompile it separately.  Then run the deployment script again.

Full error text below:
> 2023-12-20T14:44:23.920269Z ERROR apply:ext: evm::cheatcodes: non-empty stderr args=["npx", "@openzeppelin/defender-deploy-client-cli@0.0.1-alpha.0", "deploy", "--contractName", "MyContractName", "--contractPath", "test/contracts/MyContractFile.sol", "--chainId", "84531", "--artifactFile", "out/build-info/7abe818c77d7ceb2e81e23d560c4d690.json", "--licenseType", "MIT"] stderr="npm WARN exec The following package was not found and will be installed: @openzeppelin/defender-deploy-client-cli@0.0.1-alpha.0\n/Users/eric/.npm/_npx/b4571ac604df0b0a/node_modules/@openzeppelin/defender-sdk-base-client/lib/api/api.js:10\n    return Promise.reject(new api_error_1.DefenderApiResponseError(axiosError));\n                          ^\n\nDefenderApiResponseError: Request failed with status code 413\n    at rejectWithDefenderApiError (/Users/eric/.npm/_npx/b4571ac604df0b0a/node_modules/@openzeppelin/defender-sdk-base-client/lib/api/api.js:10:27)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async DeployClient.apiCall (/Users/eric/.npm/_npx/b4571ac604df0b0a/node_modules/@openzeppelin/defender-sdk-base-client/lib/api/client.js:44:20)\n    at async deployContract (/Users/eric/.npm/_npx/b4571ac604df0b0a/node_modules/@openzeppelin/defender-deploy-client-cli/dist/deployContract.js:29:22)\n    at async main (/Users/eric/.npm/_npx/b4571ac604df0b0a/node_modules/@openzeppelin/defender-deploy-client-cli/dist/defender.js:32:25)\n    at async run (/Users/eric/.npm/_npx/b4571ac604df0b0a/node_modules/@openzeppelin/defender-deploy-client-cli/dist/cli.js:6:5) {\n  request: { path: '/v2/deployments', method: 'POST' },\n  response: {\n    status: 413,\n    statusText: 'Payload Too Large',\n    data: 'HTTP content length exceeded 10485760 bytes.'\n  }\n}\n\nNode.js v18.18.2\n"

**Comment by ericglau** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/commit/bd03f00eb43691b65019e7030bac329cfeb92b28
